export let data = [
    {
        id: 0,
        title: 'Mount Fuji',
        location: 'Japan',
        from: new Date(2021, 0, 12),
        to: new Date(2021, 0, 24),
        description: 'Iconic Japanese volcano, 3,776m tall. Scenic, symmetrical cone shape. UNESCO site, cultural significance. Inspires artists, climbers. Symbolizes strength, beauty.',
        img: 'Japan.jpg',
    },
    {
        id: 1,
        title: 'Great Wall of China',
        location: 'China',
        from: new Date(2021, 3, 15),
        to: new Date(2021, 3, 30),
        description: 'Ancient series of walls and fortifications. UNESCO World Heritage site. More than 2,300 years old. Cultural and historical significance. Symbolizes resilience and innovation.',
        img: 'Great_wall_of_china.jfif',
    },
    {
        id: 2,
        title: 'Eiffel Tower',
        location: 'France',
        description: 'Iconic iron lattice tower in Paris. Landmark of the city and country. Represents the artistic and engineering prowess of France.',
        img: 'Eiffel_tower.jpg',
    },
    {
        id: 3,
        title: 'Grand Canyon',
        location: 'USA',
        from: new Date(2021, 7, 10),
        to: new Date(2021, 7, 24),
        description: 'Massive canyon carved by the Colorado River. Exhibits millions of years of geological history. Known for its visually overwhelming size and intricate and colorful landscape.',
        img: 'Grand_canyon.webp',
    },
    {
        id: 4,
        title: 'Taj Mahal',
        location: 'India',
        description: 'White marble mausoleum on the right bank of the Yamuna river. UNESCO World Heritage site. Symbol of love and dedication.',
        img: 'Taj_mahal.webp',
    },
    {
        id: 5,
        title: 'Pyramids of Giza',
        location: 'Egypt',
        from: new Date(2021, 11, 7),
        description: 'Last of the Seven Wonders of the Ancient World still in existence. Known for their architectural sophistication and alignment with celestial bodies.',
        img: 'Pyramids_of_giza.avif',
    },
    {
        id: 6,
        title: 'Mount Fuji',
        location: 'Japan',
        from: new Date(2021, 0, 12),
        to: new Date(2021, 0, 24),
        description: 'Iconic Japanese volcano, 3,776m tall. Scenic, symmetrical cone shape. UNESCO site, cultural significance. Inspires artists, climbers. Symbolizes strength, beauty.',
        img: 'Japan.jpg',
    },
    {
        id: 7,
        title: 'Great Wall of China',
        location: 'China',
        from: new Date(2021, 3, 15),
        to: new Date(2021, 3, 30),
        description: 'Ancient series of walls and fortifications. UNESCO World Heritage site. More than 2,300 years old. Cultural and historical significance. Symbolizes resilience and innovation.',
        img: 'Great_wall_of_china.jfif',
    },
    {
        id: 8,
        title: 'Eiffel Tower',
        location: 'France',
        description: 'Iconic iron lattice tower in Paris. Landmark of the city and country. Represents the artistic and engineering prowess of France.',
        img: 'Eiffel_tower.jpg',
    },
    {
        id: 9,
        title: 'Grand Canyon',
        location: 'USA',
        from: new Date(2021, 7, 10),
        to: new Date(2021, 7, 24),
        description: 'Massive canyon carved by the Colorado River. Exhibits millions of years of geological history. Known for its visually overwhelming size and intricate and colorful landscape.',
        img: 'Grand_canyon.webp',
    },
    {
        id: 10,
        title: 'Taj Mahal',
        location: 'India',
        description: 'White marble mausoleum on the right bank of the Yamuna river. UNESCO World Heritage site. Symbol of love and dedication.',
        img: 'Taj_mahal.webp',
    },
    {
        id: 11,
        title: 'Pyramids of Giza',
        location: 'Egypt',
        from: new Date(2021, 11, 7),
        description: 'Last of the Seven Wonders of the Ancient World still in existence. Known for their architectural sophistication and alignment with celestial bodies.',
        img: 'Pyramids_of_giza.avif',
    },
];
